import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./src/css/globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Nav from "./components/navbar";
import Side from "./components/sideBar";
import { Col, Row } from "antd";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "2eic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Nav /> */}
        <Row>
          <Col span={4}>
            <Side />
          </Col>
          <Col span={20}>
            <AntdRegistry>{children}</AntdRegistry>
          </Col>
        </Row>
      </body>
    </html>
  );
}
